### ISSUE TITLE
switch testing framework for pytest to abseil

### ISSUE THREAD

**Issue by SinaChavoshi** [tensorflow/cloud#143]
https://abseil.io/docs/python/guides/testing, this will allow us to benefit from some of the test automated infrastructure namely be able to share nicely formatted test results back on GH for integration tests.

**Comment by ucdmkt** [comment]
One of the benefit of abseil testing framework is [ability to parameterize](https://github.com/abseil/abseil-py/blob/master/absl/testing/parameterized.py) test cases. We could potentially remove lots of repetition.

 For other parts, I believe it's almost (completely?) upward compatible with unittest, so it should be mostly drop-in replacement.
