### ISSUE TITLE
Support Cloud Build

### ISSUE THREAD

**Issue by gogasca** [tensorflow/cloud#15]
Since images are built locally then pushed to GCR, for limited local resources will be nice to add support to build in GCR and then Train model. With this method the Docker image is built in Google Cloud infrastructure. 
Google Cloud Build: https://cloud.google.com/cloud-build/docs/running-builds/start-build-manually#api

**Comment by pavithrasv** [comment]
Great coincidence :) I added support for cloud build already. Please take a look!
