### ISSUE TITLE
TensorFlow Cloud on Colab

### ISSUE THREAD

**Issue by m3sibti** [tensorflow/cloud#20]
Is there any way of using this tensorflow-cloud repository on Google Colab?

**Comment by pavithrasv** [comment]
Hello @m3sibti , yes. This is supported on colab. Please see https://github.com/tensorflow/cloud#usage-guide #4. We will add an example for this very soon.

**Comment by pavithrasv** [comment]
Please checkout colab example: https://github.com/tensorflow/cloud/blob/master/tests/integration/call_run_within_nb_on_colab.ipynb

Thank you!
