### ISSUE TITLE
cloud build fail when tf-nightly installed locally

### ISSUE THREAD

**Issue by yixingfu** [tensorflow/cloud#29]
In an environment with tf-nightly, trying to run tfc with cloud build fails. 

The failure is caused by dockerfile use version to determine base image. In the case of tf-nightly, it gives something like 2.x.0-dev2020mmdd. 

It should be good to check if corresponding image exist before starting build, and throw relevant error message. Also, for the case of nightly build, can we just use nightly for all versions labeled with 'dev'?

**Comment by pavithrasv** [comment]
Fixed in https://github.com/tensorflow/cloud/pull/30
