### ISSUE TITLE
Instructions missing

### ISSUE THREAD

**Issue by gogasca** [tensorflow/cloud#6]
Looks like you need to define:
1. GCP Project
2. GCP authentication
3. Google Cloud SDK
4. Docker client 

I can submit a PR with the requirements.

**Comment by LGTcoder** [comment]
true...same as mentioned

**Comment by gogasca** [comment]
Nit: Added https://github.com/tensorflow/cloud/pull/11

**Comment by pavithrasv** [comment]
Added more instructions in README doc. Thank you!
