### ISSUE TITLE
version is specified in both __init__.py and setup.py

### ISSUE THREAD

**Issue by SinaChavoshi** [tensorflow/cloud#73]
This is a quick clean up filing this for tracking ... should preferably be only maintained in one location.

**Comment by ucdmkt** [comment]
FYI, one way to address this is to create a `version.py` inside the module as the source of truth, and reference it from `setup.py`.

[Reference](https://github.com/tensorflow/tfx/blob/master/setup.py#L124)

**Comment by pavithrasv** [comment]
Fixed in https://github.com/tensorflow/cloud/pull/118
