### ISSUE TITLE
Exclude tests from setup.py

### ISSUE THREAD

**Issue by SinaChavoshi** [tensorflow/cloud#81]
Test files are currently included in the pypi package, this is to update the setup.py file to exclude tests. 

```python
find_packages("core", exclude=["tests"])
```
Alternatively we can move tests folder up to /python.

**Comment by ucdmkt** [comment]
> Alternatively we can move tests folder down to /python.

I think you meant to move tests folder 'up'.

**Comment by SinaChavoshi** [comment]
Thank you, corrected the comment accordingly to avoid confusion.

**Comment by pavithrasv** [comment]
setup.py excludes tests already as `packages=find_packages(exclude=("src/python/tests",)),`
